---
sudo: required

env:
  - distro: rhel
    version: 7
    container: "registry.access.redhat.com/rhel7"
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock"
    ansible_opts: "--extra-vars @/etc/ansible/roles/role_under_test/tests/extra_vars.yml"
  - distro: centos
    version: 7
    container: "centos:7"
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro --tmpfs /run --tmpfs /run/lock"
    ansible_opts: "--extra-vars @/etc/ansible/roles/role_under_test/tests/extra_vars.yml"

services: docker

before_install:
  # Pull container.
  - 'docker pull ${container}'
  - 'docker build --rm=true --file=tests/Dockerfile.${distro}-${version} --tag=${distro}-${version}:ansible tests'

script:
  - container_id=$(mktemp)

  # Run container in detached state.
  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} ${distro}-${version}:ansible "${init}" > "${container_id}"'

  # Register with Red Hat
  - 'if [ ${distro} = "rhel" ]; then
        rhsm=$(mktemp);
        sudo docker exec "$(cat ${container_id})" subscription-manager register --username=$RHN_USERNAME --password=$RHN_PASSWORD --auto-attach;
     fi'

  # Ansible syntax check.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/travis.yml --syntax-check'

  # Test role.
  - 'sudo docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/travis.yml --extra-vars @/etc/ansible/roles/role_under_test/tests/extra_vars.yml -vv'

  # Test role idempotence.
  - idempotence=$(mktemp)
  - sudo docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/travis.yml --extra-vars @/etc/ansible/roles/role_under_test/tests/extra_vars.yml | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Deregister
  - 'if [ ${distro} = "rhel" ]; then
        docker exec "$(cat ${container_id})" subscription-manager unregister;
     fi'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
