---
sudo: required
services: docker
dist: xenial
language: python
python: 3.7
before_install:
  - docker pull centos/systemd
install:
  - pip3 install -r ci-requirements.txt
script:
  - molecule test
