---
sudo: false
services: docker
dist: xenial
language: python
python:
  - 3.7
env:
  - TYPE=aws
  - TYPE=default
before_install:
  - rm -rf molecule/vagrant
  - |
    if ["$TYPE" -eq "aws"]
    then
      docker pull centos/systemd
      docker pull registry.access.redhat.com/rhel7:latest
      (cd molecule/default; docker build --build-arg rhn_user=$RHN_USERNAME --build-arg rhn_pass=$RHN_PASSWORD -t  molly .)

install:
  - pip3 install -r tests/ci-requirements.txt
script:
  - |
    molecule test --scenario-name $TYPE
