---
sudo: required
services: docker
before_install:
  - docker pull centos/systemd
  - sudo apt-get install python3 python3-pip
  - python3 -m venv .venv
  - pip3 install ci-requirements.txt
script:
  - molecule --debug test



