---
# tasks/audit_system_call.yml

- name: "MEDIUM | RHEL-07-{{ item.id }} | {{ item.create | ternary('PATCH', 'REVERT') }} | All uses of the {{ item.call }} command must be audited."
  lineinfile:
    path: "/etc/audit/rules.d/rhel7stig_system_calls.rules"
    create: yes
    owner: root
    group: root
    mode: 0600
    line: "-a always,exit -F arch={{ arch }} -S {{ item.call }} {% if item.extra_fields is defined %}{{ item.extra_fields }} {% endif %}{{ item.include_all_auids | default(false) | ternary('', '-F auid>=1000 -F auid!=4294967295 ') }}-k {{ item.key }}"
    state: "{{ item.create | ternary('present', 'absent') }}"
  with_items:
    - b64
    - b32
  loop_control:
    loop_var: arch
  notify: restart auditd
