- name: Check OS version and family
  assert:
      that: ansible_os_family == 'RedHat' and ansible_distribution_major_version | version_compare('7', '==')
      msg: "This role can only be run against RHEL/CENTOS 7. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  tags:
      - always

- name: Check ansible version
  assert:
      that: ansible_version.full | version_compare(rhel7stig_min_ansible_version, '>=')
      msg: You must use Ansible {{ rhel7stig_min_ansible_version }} or greater
  tags:
      - always

- import_tasks: prelim.yml
  become: yes
  tags:
      - prelim_tasks
      - always

- name: Include CAT I patches
  import_tasks: fix-cat1.yml
  static: no
  when: rhel7stig_cat1_patch | bool
  tags:
      - cat1
      - patch
      - high

- name: Include CAT II patches
  import_tasks: fix-cat2.yml
  static: no
  when: rhel7stig_cat2_patch | bool
  tags:
      - cat2
      - patch
      - medium

- name: Include CAT III patches
  import_tasks: fix-cat3.yml
  static: no
  when: rhel7stig_cat3_patch | bool
  tags:
      - cat3
      - patch
      - low
