---
- name: "Run pre_remediation {{ benchmark }} audit"
  goss:
    goss_path: "{{ goss_bin }}"
    path: "{{ goss_test_file }}"
    vars_path: "{{ goss_vars_path }}"
    format: "{{ goss_format | default('json') }}"
    output_file: "{{ pre_audit_outfile }}"
  failed_when: false

- name: "capture data  {{ pre_audit_outfile }}"
  command: "cat {{ pre_audit_outfile }}"
  register: pre_audit
  changed_when: false 
    
- name: Capture pre-audit result
  set_fact: 
    pre_audit_summary: "{{ pre_audit.stdout | from_json |json_query(summary) }}"
  vars:
    summary: 'summary."summary-line"'