- name: "PRELIM | RHEL-07-010010 | The file permissions, ownership, and group membership of system files and commands must match the vendor values."
  shell: 'rpm -Va | grep ''^.M'''
  args:
    warn: no
  failed_when: no
  changed_when: no
  ignore_errors: yes
  register: rhel_07_010010_audit
  when: rhel_07_010010

- name: "PRELIM | RHEL-07-010020 | The cryptographic hash of system files and commands must match vendor values."
  shell: 'rpm -Va | grep ''^..5'' | grep -E ''/.?bin/'''
  args:
      warn: no
  failed_when: no
  changed_when: no
  ignore_errors: yes
  register: rhel_07_010020_audit
  when: rhel_07_010020

- name: "PRELIM | RHEL-07-020310 | The root account must be the only account having unrestricted access to the system"
  shell: "cat /etc/passwd | awk -F: '($3 == 0 && $1 != \"root\") {i++;print $1 } END {exit i}'"
  changed_when: no
  failed_when: no
  ignore_errors: yes
  register: rhel_07_020310_audit
  when: rhel_07_020310

- name: "PRELIM | RHEL-07-021350 | Check if prelink package is installed"
  command: rpm -q prelink
  changed_when: no
  failed_when: no
  register: rhel_07_021350_prelink_installed
  when: rhel_07_021350

- name: "PRELIM | RHEL-07-040540 | There must be no .shosts files on the system."
  find:
      paths: /
      recurse: yes
      hidden: yes
      patterns: '*.shosts'
  register: rhel_07_040540_audit
  when: rhel_07_040540
  tags:
      - cat1
      - high
      - audit
      - RHEL-07-040540

- name: "PRELIM | RHEL-07-040550 | There must be no shosts.equiv files on the system."
  find:
      paths: /
      recurse: yes
      patterns: shosts.equiv
  register: rhel_07_040550_audit
  when: rhel_07_040550
  tags:
      - cat1
      - high
      - audit
      - RHEL-07-040550

- name: "HIGH | RHEL-07-040800 | AUDIT | SNMP community strings must be changed from the default."
  command: grep {{ item }} /etc/snmp/snmpd.conf
  failed_when: no
  changed_when: no
  ignore_errors: yes
  with_items:
      - public
      - private
  register: rhel_07_040800_audit
  when: rhel_07_040800
  tags:
      - cat1
      - high
      - audit
      - RHEL-07-040800
      - snmp
