version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "ci-requirements.txt" }}

      - setup_remote_docker:
          version: 18.06.0-ce

      - run:
          name: Install python deps
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip3 install -r ci-requirements.txt

      - save_cache:
          key: dependency-cache-{{ checksum "ci-requirements.txt" }}
          paths:
            - venv
      - run:
          name: Molecule Test
          command: |
            . .venv/bin/activate
            molecule --debug test
