- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: reboot system
  shell: sleep 3; reboot
  async: 15
  poll: 0

- name: restart snmpd
  service:
      name: snmpd
      state: restarted

- name: make grub2 config
  command: grub2-mkconfig --output={{ rhel7stig_grub_cfg_path }}
  when:
      - not rhel7stig_skip_for_travis

- name: "restart {{ rhel7stig_time_service }}"
  service:
      name: "{{ rhel7stig_time_service }}"
      state: restarted

- name: init aide status
  async_status:
    jid: "{{ rhel7stig_aide_init_status.ansible_job_id }}"
  register: rhel7stig_aide_init_job_result
  until: rhel7stig_aide_init_job_result.finished
  retries: 60
  delay: 5
  tags:
    - aide

- name: restart auditd
  command: service auditd restart
  args:
     warn: no
  when:
      - rhel7stig_skip_for_travis == false

- name: rebuild initramfs
  command: dracut -f

- name: undo existing prelinking
  command: prelink -ua

- name: update running audit failure mode
  command: auditctl -f {{ rhel7stig_auditd_failure_flag }}
  failed_when: no
