---
driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: centos-vagrant
    box: centos/7
  - name: rhel-vagrant
    box: rhel7

scenario:
  name: vagrant
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence # Current bug with lineinfile module
    - side_effect
    - verify
    - destroy

verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: false
