---
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      ignore: |
        /home/circleci/project/venv/*
        /home/circleci/project/src/*
      extends: relaxed
      rules:
        braces:
          max-spaces-inside: 1
          level: error
        brackets:
          max-spaces-inside: 1
          level: error
        line-length: disable

platforms:
  - name: instance
    image: centos/systemd
    image_version: latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /usr/sbin/init
    capabilities:
      - ALL
    privileged: true
    pull: true
    groups:
      - docker

provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    #- idempotence # Current bug with lineinfile module
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: false
