---
- name: Set SSH username
  hosts: all
  connection: local
  tasks:
    - name: add host for ssh name settings
      add_host:
        groups: prepped
        name: "{{ inventory_hostname }}"
        ansible_user: centos
      when: "'centos' in inventory_hostname"

    - name: add host for ssh name settings
      add_host:
        groups: prepped
        name: "{{ inventory_hostname }}"
        ansible_user: ec2-user
      when: "'rhel' in inventory_hostname"

- name: Converge
  hosts: prepped
  become: yes
  roles:
    - role: RHEL7-STIG
      rhel7stig_using_password_auth: false
