---
- name: Prepare Pre
  hosts: all
  tasks:
    - name: add host for ssh name settings
      add_host:
        groups: prepped
        name: "{{ inventory_hostname }}"
        ansible_user: centos
      when: "{{ 'centos' in inventory_hostname }}"

    - name: add host for ssh name settings
      add_host:
        groups: prepped
        name: "{{ inventory_hostname }}"
        ansible_user: ec2-user
      when: "{{ 'rhel' in inventory_hostname }}"


- name: Prepare
  hosts: prepped
  gather_facts: false
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal python-zipstream)
      become: true
      changed_when: false
